### ISSUE TITLE
Could you provide the json file in your example code?

### ISSUE THREAD

**Issue by HulkMaker** [Luvideria/mcfgJSONtoOBJ#4]
Dear,

It's really a nice project. I am trying jupyter files, but those json file are not found. Could you help to provide them?

**Comment by Luvideria** [comment]
The Json files you are talking about are arbitrary test files, you can create your own (on mcfg).
Since it's nice to see a jupyter notebook just "work", I included the example files as suggested.
Note that some have a river, some have walls, if you want to implement, say, rivers, you need to generate a file (with mcfg) that contains one.

**Comment by HulkMaker** [comment]
Got the files and your explanation. 
Great thanks for your kind instruction!
